snap/hooks/post-refresh: use rsync in the hook
There are currently issues with using cp -ar like this:

$ snap refresh test-snapd-ubuntu-core-initramfs
error: cannot perform the following tasks:
- Run post-refresh hook of "test-snapd-ubuntu-core-initramfs" snap if present (run hook "post-refresh": cp: cannot create regular file '/var/snap/test-snapd-ubuntu-core-initramfs/30/usr/lib/ubuntu-core-initramfs/main/usr/lib/udev/hwdb.bin': Permission denied)

This is because that file is read-only, so using rsync will only attempt to copy
this file if it is different.

Signed-off-by: Ian Johnson <ian.johnson@canonical.com>