snapcraft.yaml: try additional modules layout
This is to attempt to solve errors like:

dracut-install: ERROR: installing '/usr/lib/modules/5.4.0-12-generic'
Traceback (most recent call last):
  File "/snap/test-snapd-ubuntu-core-initramfs/x1/usr/bin/ubuntu-core-initramfs", line 186, in <module>
    main()
  File "/snap/test-snapd-ubuntu-core-initramfs/x1/usr/bin/ubuntu-core-initramfs", line 182, in main
    globals()[args.subcmd.replace("-", "_")](parser, args)
  File "/snap/test-snapd-ubuntu-core-initramfs/x1/usr/bin/ubuntu-core-initramfs", line 58, in create_initrd
    os.path.join("/usr/lib/modules", args.kernelver),
  File "/snap/test-snapd-ubuntu-core-initramfs/x1/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/lib/dracut/dracut-install', '-D', '/tmp/tmp0thaits4.ubuntu-core-initramfs/main', '--all', '/var/snap/test-snapd-ubuntu-core-initramfs/x1/repacked-kernel-31391/lib/modules/5.4.0-12-generic/modules.order', '/var/snap/test-snapd-ubuntu-core-initramfs/x1/repacked-kernel-31391/lib/modules/5.4.0-12-generic/modules.builtin', '/var/snap/test-snapd-ubuntu-core-initramfs/x1/repacked-kernel-31391/lib/modules/5.4.0-12-generic/modules.builtin.bin', '/usr/lib/modules/5.4.0-12-generic']' returned non-zero exit status 1.

which happen because /usr/lib/modules/5.4.0-12-generic may not exist in
the snap mount namespace if the installed kernel is not
5.4.0-12-generic.

Signed-off-by: Ian Johnson <person.uwsome@gmail.com>